# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: [ "strikethrough", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "space_after_headers", "underline", "highlight", "footnotes", "superscript" ]

gems:
- jemoji
- jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
title:            'Blog'
tagline:          'Oblio blog.'
description:      'Oblio rambling.'
url:              http://blog.oblio360.com

author:
  name:           'Constantin Caraivan'
  url:            https://twitter.com/oblio360

paginate:         5
