# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

gems:
- jemoji
- jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
title:            'Blog'
tagline:          'Oblio blog.'
description:      'Oblio rambling.'
url:              http://blog.oblio360.com

author:
  name:           'Constantin Caraivan'
  url:            https://twitter.com/oblio360

paginate:         5
